# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gaoxin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=8)),
                ('company', models.CharField(max_length=80)),
            ],
        ),
    ]
